version: '3.8'

services:
  test:
    build:
      dockerfile: Dockerfile.test
      context: .
      args:
        - 'HTTP_PROXY'
        - 'HTTPS_PROXY'
    depends_on:
      - mq
    command: test

  mq:
    image: 'blackglory/mq:0.7.0'
